name: mlai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pillow
  - matplotlib
  - scikit-learn
  - pyyaml
  - jupyterlab
  - pip:
      - tensorflow==2.16.*
      - opencv-python==4.9.*
      - anomalib==1.1.*
      - tflite-model-maker==0.4.*
      - onnx
      - onnx-tf
      - tensorflow-hub
      - protobuf
